### ISSUE TITLE
clientID is empty

### ISSUE THREAD

**Issue by nikoChen-I755695** [SAP/crossplane-provider-btp#93]
**Describe the bug**
We are using Composition to deploy the BTP Kyma runtime. However, we encountered an issue where the Kyma creation failed with the error: "clientID must not be empty." The relevant code is provided below. I have verified that the clientID has been correctly input through the Composition data transfer.https://github.tools.sap/rgm/co-pipeline-action-core/blob/feature-development/infrastructure/charts/templates/kymaruntime/kyma-compositions.yaml

**Tested with Provider Version**
crossplane:
      version: 1.18.0
      providers:
        - name: btp
          version: 1.0.2
        - name: kubernetes
          version: 0.15.0
        - name: ias
          version: 0.2.0
        - name: vault
          version: 1.0.0
        - name: btp-account
          version: 0.7.6
        - name: argocd
          version: 0.9.1
**To Reproduce**

**Expected behavior**
Successful creation of kyma environment

**Screenshots**
![Image](https://github.com/user-attachments/assets/b9eb5904-d612-4fa4-a2da-d6fac067633e)

**Additional context**

**Comment by JayChanggithub** [comment]
Hi Colleagues, 

In collaboration with Niko, the issue has been posted. Please refer to the full context below. We ensured that the clientID was transferred via the composition field and is visible within the forProvider manifest. However, the status shows the clientID as empty. We're unsure what happened and would like clarification on the correct setup.
```
k get kymaenvironment.environment.btp.orchestrate.cloud.sap k-sre-slow-us21-co -o yaml

spec:
  cloudManagementRef:
    name: k-sre-slow-us21-co
  cloudManagementSecret: k-sre-slow-us21-co-cis-local
  cloudManagementSecretNamespace: default
  cloudManagementSubaccountGuid: 2dbb3308-71c6-4b1b-bdbf-9e83ccc4136a
  deletionPolicy: Delete
  forProvider:
    parameters:
      administrators:
      - mossin.fan@sap.com
      - chieh-chuan.chang@sap.com
      - james.zhang08@sap.com
      - betty.ben@sap.com
      - minggong.cheng@sap.com
      - niko.chen@sap.com
      - k-sre-slow-us21-co@sap.com
      autoScalerMax: 3
      autoScalerMin: 3
      machineType: Standard_D8s_v5
      oidc:
        clientID: a7ff089c-5f56-48e8-9e1d-7ad0dc17ceaa
        groupsClaim: groups
        issuerURL: https://devexpdev.accounts.ondemand.com/
        signingAlgs:
        - RS256
        usernameClaim: email
        usernamePrefix: '-'
      region: eastus
    planName: azure
  managementPolicies:
  - '*'
  providerConfigRef:
    name: account-provider-config
  subaccountGuid: 2dbb3308-71c6-4b1b-bdbf-9e83ccc4136a
  subaccountRef:
    name: k-sre-slow-us21-co
  writeConnectionSecretToRef:
    name: k-sre-slow-us21-co-kyma-environment
    namespace: default
status:
  atProvider:
    brokerId: 1B1719DE-CC81-4686-A9E2-4631AA82D2BD
    createdDate: "1736321269760.000000"
    customLabels: {}
    description: created via crossplane-provider-btp-account
    environmentType: kyma
    globalAccountGUID: 2291c59f-008e-432d-a082-e3b49f9b5e26
    id: BC1ADB06-8997-4F95-A56D-7F731B143577
    modifiedDate: "1736321269760.000000"
    name: k-sre-slow-us21-co
    parameters: '{"administrators":["k-sre-slow-us21-co@sap.com"],"autoScalerMax":3,"autoScalerMin":3,"machineType":"Standard_D8s_v5","name":"k-sre-slow-us21-co","oidc":{"clientID":"","groupsClaim":"groups","issuerURL":"https://devexpdev.accounts.ondemand.com/","signingAlgs":["RS256"],"usernameClaim":"email","usernamePrefix":"-"},"orchestrate.cloud.sap/subaccount-operator":"ef2997b3-146e-453d-a109-7e65b86c7874","region":"eastus"}'
```

**Comment by sdischer-sap** [comment]
I just tried to reproduce that with exactly your data (apart from the users of course) and everything worked smoothly. I was using the latest version though.

Do you have some other kyma environments to check against? 
I noticed you are still using resources of the innersource provider, despite having the open source provider installed as well. Ideally try another one with the latest version of the open source provider to make sure there are no issues there.

**Comment by JayChanggithub** [comment]
@sdischer-sap  
Today, we tried to provision the new environments using the composition method, but the problem occurred again. if you have feel free to take look?

<img width="1785" alt="Image" src="https://github.com/user-attachments/assets/4854cbee-025c-4f73-80c7-32c3e1ac45a9" />

**Comment by sdischer-sap** [comment]
@JayChanggithub just checked your cluster. While I can't see exactly this error I do see that your `KymaEnvironment` is in a failure state. This is most likely due to an issue that is causing continuous updates, which recently has been fixed in v1.0.3.  Of the provider. 

Sorry to ask you again, but could you upgrade to this latest version. It has been released yesterday and fixes some Kyma issues. Maybe yours have been related to the same issues after all. After you have done the version update your Kyma instance in BTP will most likely still be in a failure state. To get rid of that please do a manual update of the instance in BTP cockpit without changing any parameters. This should get rid of the failure state and the provider will pick up the normal reconcilation of the instance.

**Comment by JayChanggithub** [comment]
@sdischer-sap Sure, Let me upgrade to v1.0.3 and also try again composition way to ensure whether reconcile as well as inject parameters normally.

**Comment by JayChanggithub** [comment]
@sdischer-sap after we upgrade to v1.0.3  the issue which regarding https://github.tools.sap/CoLa/support/issues/190#issuecomment-10489805 should be fix. However the clientID is empty and also https://github.com/SAP/crossplane-provider-btp/issues/96 are still exist.

**Comment by sdischer-sap** [comment]
@JayChanggithub 
After resolving the other issues about continous updates we are back on this issue. 
So I see in your KymaEnvironment `k-sre-dev-us21-co` that there is no `clientID` in the spec as well as in the observation. 

From the providers point of view this is correct. It passes the data from the spec to the API and saves back the API response in the observation. So I guess there is an error in generating the spec from the composition. Please doublecheck that parts. When the spec is being filled with the clientID it should work.

**Comment by JayChanggithub** [comment]
@ sdischer-sap Let me check it. Also, our composition can be found here: [Kyma Composition](https://github.tools.sap/rgm/co-pipeline-action-core/blob/main/composition/kymaruntime/kyma-compositions.yaml), and the XRD is available here: [Kyma XRD](https://github.tools.sap/rgm/co-pipeline-action-core/blob/main/composition/xrd/kyma-xrd.yaml#L30).

I'm not sure why the clientID isn't being transferred correctly, even though we've defined the properties as shown in the XRD above.

**Comment by JayChanggithub** [comment]
```
k get kymaenvironment.sre.tools.sap -oyaml                                                                                                                                                                       [10:41:49]
apiVersion: v1
items:
- apiVersion: sre.tools.sap/v1alpha1
  kind: KymaEnvironment
  metadata:
    annotations:
      meta.helm.sh/release-name: default-helmrelease
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2025-02-21T02:54:48Z"
    finalizers:
    - finalizer.apiextensions.crossplane.io
    generation: 4
    labels:
      app.kubernetes.io/managed-by: Helm
      helm.toolkit.fluxcd.io/name: helmrelease
      helm.toolkit.fluxcd.io/namespace: default
    name: k-sre-dev-us21-co
    namespace: default
    resourceVersion: "24741905"
    uid: 5aeb941d-d100-4e55-921e-791ebe2e9e4d
  spec:
    compositeDeletePolicy: Foreground
    compositionRef:
      name: sre-kyma-environment
    compositionRevisionRef:
      name: sre-kyma-environment-dde6752
    compositionUpdatePolicy: Automatic
    kymaParameters:
      administrators:
      - chieh-chuan.chang@sap.com
      - james.zhang08@sap.com
      - niko.chen@sap.com
      - k-sre-dev-us21-co@sap.com
      autoScalerMax: 3
      autoScalerMin: 3
      machineType: Standard_D8s_v5
      region: eastus
    resourceRef:
      apiVersion: sre.tools.sap/v1alpha1
      kind: XKymaEnvironment
      name: k-sre-dev-us21-co-f8766
    servicePlanName: azure
    subaccountName: k-sre-dev-us21-co
  status:
    conditions:
    - lastTransitionTime: "2025-02-21T02:54:48Z"
      reason: ReconcileSuccess
      status: "True"
      type: Synced
    - lastTransitionTime: "2025-02-21T02:54:48Z"
      message: Claim is waiting for composite resource to become Ready
      reason: Waiting
      status: "False"
      type: Ready
kind: List
metadata:
  resourceVersion: ""
```

**Comment by sdischer-sap** [comment]
@JayChanggithub 
I am not sure what you are asking. This composition isn't written by us, so I can't really tell what reasoning it should follow. You need to make sure that the clientID transferred to the kyma spec in `spec.forProvider.parameters.oidc.clientID`

**Comment by sdischer-sap** [comment]
@JayChanggithub  Is this issue being resolved?

**Comment by JayChanggithub** [comment]
@sdischer-sap 
Colleagues will validate again in couple of days. If anything feedback regarding that I will back to here. Thanks.

**Comment by sdischer-sap** [comment]
any news here?

**Comment by JayChanggithub** [comment]
Hi @sdischer-sap  
The issue had been fixed. Since the fluxCD specific feature updated. Thanks. 

```
driftDetection:
      mode: enabled
```
